version: '3'

services:
  bot:
    build: .
    volumes:
      - .:/bot
      - ./node_modules:/bot/node_modules
    ports:
      - 4000:4000
    command: npm run dev
    environment:
      ACCESS_TOKEN_MESSENGER: <token_messenger>
  ngrok:
    image: wernight/ngrok
    ports:
      - "0.0.0.0:4040:4040"
    environment:
      # https://github.com/wernight/docker-ngrok
      NGROK_AUTH: <AUTH>
      NGROK_PORT: "bot:4000"
    links:
      - bot
