FROM node:12.3.0

RUN apt-get update && apt-get install -y build-essential

RUN mkdir -p /bot

WORKDIR /bot
COPY package.json /bot
COPY package-lock.json /bot
COPY node_modules /bot/node_modules
RUN npm install

COPY . ./bot
